# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosFamiliar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ced_f', models.IntegerField(unique=True, verbose_name='C\xe9dula')),
                ('nom_f', models.CharField(blank=True, max_length=45, null=True, verbose_name='Nombre')),
                ('apell_f', models.CharField(blank=True, max_length=45, null=True, verbose_name='Apellido')),
                ('fecha_naci', models.DateField(null=True, verbose_name='Fecha de nacimiento')),
                ('nivel_intr', models.CharField(blank=True, max_length=45, null=True, verbose_name='Nivel de intrucci\xf3n')),
                ('ocupacion', models.CharField(blank=True, max_length=45, null=True, verbose_name='Ocupaci\xf3n')),
                ('ingreso_mensual', models.IntegerField(verbose_name='Ingreso mensual')),
                ('relationship', models.CharField(choices=[(b'PADRE', b'PADRE'), (b'MADRE', b'MADRE'), (b'HERMANO', b'HERMANO'), (b'HERMANA', b'HERMANA'), (b'TIO', b'TIO'), (b'TIA', b'TIA'), (b'ABUELO', b'ABUELO'), (b'ABUELA', b'ABUELA'), (b'HIJO', b'HIJO'), (b'HIJA', b'HIJA')], max_length=45, verbose_name='Parentesco')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
