# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(blank=True, max_length=500, null=True)),
                ('constancia', models.FileField(blank=True, upload_to='anexo_costancia')),
                ('presupuesto', models.FileField(blank=True, upload_to='anexo_presupuesto')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
