# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vivienda', models.CharField(blank=True, choices=[(b'', b'Tipo de Hogar'), (b'CASA', b'CASA'), (b'QUINTA', b'QUINTA'), (b'APARTAMENTO', b'APARTAMENTO'), (b'RANCHO', b'RANCHO'), (b'HABITACION', b'HABITACION')], max_length=20, null=True, verbose_name='TIPO DE VIVIENDA')),
                ('tenencia_vivienda', models.CharField(blank=True, choices=[(b'', b'Tipo de Tenencia'), (b'PROPIA', b'PROPIA'), (b'ALQUILADA', b'ALQUILADA'), (b'PRESTADA', b'PRESTADA'), (b'HEREDADA', b'HEREDADA'), (b'INVASION', b'INVASION')], max_length=20, null=True, verbose_name='TENENCIA DE LA VIVIENDA')),
                ('num_dormitorio', models.IntegerField(blank=True, default=0, null=True, verbose_name='NUMERO DE DORMITORIO')),
                ('sala_di', models.BooleanField(verbose_name='SALA')),
                ('cocina_di', models.BooleanField(verbose_name='COCINA')),
                ('comedor_di', models.BooleanField(verbose_name='COMEDOR')),
                ('bano_di', models.BooleanField(verbose_name='BA\xd1O')),
                ('lavadero_di', models.BooleanField(verbose_name='LAVADERO')),
                ('patio_di', models.BooleanField(verbose_name='PATIO')),
                ('garaje_di', models.BooleanField(verbose_name='GARAJE')),
                ('jardin_di', models.BooleanField(verbose_name='JARDIN')),
                ('nevera_eq', models.IntegerField(blank=True, default=0, null=True, verbose_name='NEVERA(S)')),
                ('cocina_eq', models.IntegerField(blank=True, default=0, null=True, verbose_name='COCINA(S)')),
                ('tv_eq', models.IntegerField(blank=True, default=0, null=True, verbose_name='TELEVISOR(ES)')),
                ('dvd_eq', models.IntegerField(blank=True, default=0, null=True, verbose_name='DVD')),
                ('ventiladores_eq', models.IntegerField(blank=True, default=0, null=True, verbose_name='VENTILADOR(ES)')),
                ('a_a_eq', models.IntegerField(blank=True, default=0, null=True, verbose_name='AIRE ACONDICIONADO')),
                ('computadora_eq', models.IntegerField(blank=True, default=0, null=True, verbose_name='COMPUTADORA(S)')),
                ('lavadora_eq', models.IntegerField(blank=True, default=0, null=True, verbose_name='LAVADORA')),
                ('recibo_eq', models.IntegerField(blank=True, default=0, null=True, verbose_name='RECIBO')),
                ('comedor_eq', models.IntegerField(blank=True, default=0, null=True, verbose_name='COMEDOR(ES)')),
                ('camas_eq', models.IntegerField(blank=True, default=0, null=True, verbose_name='CAMA(S)')),
                ('agua_se', models.BooleanField(verbose_name='AGUA')),
                ('red_cloacas_se', models.BooleanField(verbose_name='RED DE CLOACAS')),
                ('electricidad_se', models.BooleanField(verbose_name='ELECTRICIDAD')),
                ('internet_se', models.BooleanField(verbose_name='INTERNET')),
                ('tv_cable_se', models.BooleanField(verbose_name='TV POR CABLE')),
                ('telefono_se', models.BooleanField(verbose_name='TELEFONO')),
                ('trans_publico_se', models.BooleanField(verbose_name='TRANSPORTE PUBLICO')),
                ('aseo_urba_se', models.BooleanField(verbose_name='ASEO URBANICO')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
