# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-20 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivienda', '0002_auto_20170818_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='num_dormitorio',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='NUMERO DE DORMITORIO'),
        ),
    ]
